//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_ImportBIProd
    {
        public long BIPReportId { get; set; }
        public Nullable<long> RepId { get; set; }
        public string Group { get; set; }
        public string UserIdName { get; set; }
        public string BusinessArea { get; set; }
        public string WorkType { get; set; }
        public string Status { get; set; }
        public Nullable<int> Count { get; set; }
        public string Date1 { get; set; }
        public string Date2 { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<long> TeamId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string UploadedBy { get; set; }
    }
}
