//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_Representative
    {
        public long RepId { get; set; }
        public string PRDUserId { get; set; }
        public string AIQUserId { get; set; }
        public string BIUserId { get; set; }
        public Nullable<long> WorkdayId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> TeamId { get; set; }
        public Nullable<int> CoreRoleId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> OnShoreRep { get; set; }
        public Nullable<bool> PhoneRep { get; set; }
        public Nullable<double> WorkHours { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> HasPrevious { get; set; }
        public Nullable<long> PreviousId { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public bool IsActive { get; set; }
    }
}
