//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_TeamScorecard_Current
    {
        public long TeamScorecardId { get; set; }
        public long TeamId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public string IndividualSummaryComments { get; set; }
        public string TeamSummaryComments { get; set; }
        public string WorktypeSummaryComments { get; set; }
        public string StatusSummaryComments { get; set; }
        public bool IsSignedOff { get; set; }
        public string ManagerSignOff { get; set; }
        public string SignOffBy { get; set; }
        public Nullable<System.DateTime> SignOffDate { get; set; }
        public Nullable<double> ProductivityGoal { get; set; }
        public Nullable<double> QualityGoal { get; set; }
        public Nullable<double> EfficiencyGoal { get; set; }
        public Nullable<double> UtilizationGoal { get; set; }
    }
}
