
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OPSCO_Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OSC_IndividualScorecard_Current
{

    public long IndividualScorecardId { get; set; }

    public Nullable<long> RepId { get; set; }

    public Nullable<long> TeamId { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> Year { get; set; }

    public string Comments { get; set; }

}

}
