//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_Team
    {
        public long TeamId { get; set; }
        public string TeamName { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public bool IsActive { get; set; }
        public string BIUserGroup { get; set; }
        public string AIQUserGroup { get; set; }
    }
}
