//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_NptCategory
    {
        public long CategoryId { get; set; }
        public string CategoryDesc { get; set; }
        public bool IsCategory { get; set; }
        public bool IsSubCategory { get; set; }
        public Nullable<long> Category { get; set; }
        public bool IsActive { get; set; }
    }
}
