
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OPSCO_Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OSC_ImportTA
{

    public long TAReportId { get; set; }

    public Nullable<long> RepId { get; set; }

    public string AssignedId { get; set; }

    public string Group { get; set; }

    public string FirstName { get; set; }

    public string MiddleInt { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> CreateDateTime { get; set; }

    public string BusinessArea { get; set; }

    public string WorkType { get; set; }

    public string Status { get; set; }

    public string Queue { get; set; }

    public string Suspended { get; set; }

    public Nullable<System.DateTime> SuspendDate { get; set; }

    public Nullable<System.DateTime> UnsuspendDate { get; set; }

    public Nullable<decimal> LastStatusUpdate { get; set; }

    public string Account { get; set; }

    public string GAC { get; set; }

    public string Assoc { get; set; }

    public string Certificate { get; set; }

    public Nullable<decimal> CheckAmount { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string CustomerNo { get; set; }

    public string ProductType { get; set; }

    public string AdminSystem { get; set; }

    public Nullable<decimal> CheckAmountTotal { get; set; }

    public string UCIVendorMatchDate { get; set; }

    public string ReasonCodeForAdv { get; set; }

    public string ReasonDescription { get; set; }

    public string TinSourceType { get; set; }

    public string SSBusinessUnit { get; set; }

    public Nullable<long> TeamId { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<System.DateTime> DateUploaded { get; set; }

    public string UploadedBy { get; set; }

}

}
