
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OPSCO_Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OSC_CoreRole
{

    public int CoreRoleId { get; set; }

    public string CoreRole { get; set; }

    public Nullable<int> Tier { get; set; }

    public Nullable<double> MonthlyHours { get; set; }

    public Nullable<double> Percentage { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
