//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_ManualEntry
    {
        public long EntryId { get; set; }
        public Nullable<long> TeamId { get; set; }
        public Nullable<long> RepId { get; set; }
        public Nullable<decimal> GainLossOccurances { get; set; }
        public Nullable<double> GainLossAmount { get; set; }
        public Nullable<double> CallManagementScore { get; set; }
        public string ProjectResponsibility { get; set; }
        public Nullable<double> ScheduleAdherence { get; set; }
        public Nullable<double> Compliance { get; set; }
        public Nullable<double> ProductAccuracy { get; set; }
        public Nullable<double> Commitment { get; set; }
        public Nullable<double> JHValues { get; set; }
        public Nullable<double> CallEfficiency { get; set; }
        public Nullable<double> Engagement { get; set; }
        public Nullable<double> AdministrativeProcedures { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string UploadedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ActiveProjects { get; set; }
        public Nullable<int> CompletedProjects { get; set; }
    }
}
