
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OPSCO_Web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OSC_WorkStatus
{

    public long StatusId { get; set; }

    public string StatusCode { get; set; }

    public string StatusDescription { get; set; }

    public bool IsActive { get; set; }

}

}
