//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_ActivityTracker
    {
        public long ActivityId { get; set; }
        public long RepId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Activity { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<double> NoOfDays { get; set; }
        public long TeamId { get; set; }
        public bool IsActive { get; set; }
    }
}
