//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSC_CompletedWorkItem
    {
        public long CompletedWorkItemId { get; set; }
        public long WorkItemNo { get; set; }
        public long CompletedUnitId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public long TeamId { get; set; }
    }
}
