//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSCO_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OSCEntities : DbContext
    {
        public OSCEntities()
            : base("name=OSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OSC_ActivityTracker> OSC_ActivityTracker { get; set; }
        public virtual DbSet<OSC_BusinessArea> OSC_BusinessArea { get; set; }
        public virtual DbSet<OSC_CoreRole> OSC_CoreRole { get; set; }
        public virtual DbSet<OSC_Department> OSC_Department { get; set; }
        public virtual DbSet<OSC_ImportAIQ> OSC_ImportAIQ { get; set; }
        public virtual DbSet<OSC_ImportBIProd> OSC_ImportBIProd { get; set; }
        public virtual DbSet<OSC_ImportBIQual> OSC_ImportBIQual { get; set; }
        public virtual DbSet<OSC_ImportNPT> OSC_ImportNPT { get; set; }
        public virtual DbSet<OSC_ImportTA> OSC_ImportTA { get; set; }
        public virtual DbSet<OSC_IndividualScorecard_Current> OSC_IndividualScorecard_Current { get; set; }
        public virtual DbSet<OSC_Manager> OSC_Manager { get; set; }
        public virtual DbSet<OSC_ManualEntry> OSC_ManualEntry { get; set; }
        public virtual DbSet<OSC_NptCategory> OSC_NptCategory { get; set; }
        public virtual DbSet<OSC_Representative> OSC_Representative { get; set; }
        public virtual DbSet<OSC_Team> OSC_Team { get; set; }
        public virtual DbSet<OSC_WorkStatus> OSC_WorkStatus { get; set; }
        public virtual DbSet<OSC_WorkType> OSC_WorkType { get; set; }
        public virtual DbSet<OSC_ScorecardField> OSC_ScorecardField { get; set; }
        public virtual DbSet<OSC_CustomizeScorecard> OSC_CustomizeScorecard { get; set; }
        public virtual DbSet<OSC_ManageGroup> OSC_ManageGroup { get; set; }
        public virtual DbSet<OSC_TeamGroupIds> OSC_TeamGroupIds { get; set; }
        public virtual DbSet<OSC_TeamNptCategory> OSC_TeamNptCategory { get; set; }
        public virtual DbSet<OSC_TeamScorecard_Current> OSC_TeamScorecard_Current { get; set; }
        public virtual DbSet<OSC_Location> OSC_Location { get; set; }
        public virtual DbSet<OSC_TeamWorkItem> OSC_TeamWorkItem { get; set; }
    }
}
